### ISSUE TITLE
In FocusSpec, loop only over existing fibers

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/megaradrp#111]
...
numina.recipes.megara INFO start result generation
DEBUG: cwd to original path: '/Users/agpaz/Desktop/AIV/test_pipeline/14_MR-RI'
Traceback (most recent call last):
  File "/Users/agpaz/anaconda2/envs/megara/bin/numina", line 11, in <module>
    load_entry_point('numina==0.15.dev1', 'console_scripts', 'numina')()
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/cli.py", line 123, in main
    args.command(args, extra_args)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirun.py", line 86, in mode_run_obsmode
    mode_run_common(args, extra_args, mode='obs')
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 64, in mode_run_common
    return mode_run_common_obs(args, extra_args)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 177, in mode_run_common_obs
    workenv=workenv, task_control=task_control)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 214, in run_recipe
    completed_task = run_recipe_timed(recipe, rinput, task)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 232, in run_recipe_timed
    result = recipe.run(rinput)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/core/validator.py", line 30, in mod_run
    result = method(self, ri)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/megaradrp-0.6.dev1-py2.7.egg/megaradrp/recipes/auxiliary/focusspec.py", line 122, in run
    focus_wavelength = self.generateJSON(ever, rinput.wlcalib, obresult.frames)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/megaradrp-0.6.dev1-py2.7.egg/megaradrp/recipes/auxiliary/focusspec.py", line 228, in generateJSON
    res = polyval(arco[0], wlfib[fiber].coeff)
KeyError: 263

**Comment by sergiopasra** [comment]
FYI @guaix-ucm/megara-drp

**Comment by sergiopasra** [comment]
Should be fixed here b8e06d77d9d33876cf58fedc57a1ddc9fd4008e6
