### ISSUE TITLE
main_plus_poly.py fails

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/megaradrp#113]
(megara) bash-3.2$ python main_plus_poly.py focus_wavelength.json 
Traceback (most recent call last):
  File "main_plus_poly.py", line 168, in <module>
    generar_xls()
  File "main_plus_poly.py", line 126, in generar_xls
    read_json(file_name)
  File "main_plus_poly.py", line 61, in read_json
    contents = data['contents']
KeyError: 'contents'

**Comment by sergiopasra** [comment]
@guaix-ucm/megara-drp
