### ISSUE TITLE
We have to pair 20 miising fibers

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/megaradrp#115]
megaradrp.recipes.calibration.trace DEBUG pseudoslit box: 6a, id: 15
megaradrp.recipes.calibration.trace DEBUG matched 21     missing: 0
megaradrp.recipes.calibration.trace DEBUG pseudoslit box: 7a, id: 16
megaradrp.recipes.calibration.trace DEBUG matched 1      missing: 20
megaradrp.recipes.calibration.trace DEBUG we have to pair 20 miising fibers
DEBUG: cwd to original path: '/Users/agpaz/Desktop/AIV/test_pipeline/MOS/ThNe/MR-R'
Traceback (most recent call last):
  File "/Users/agpaz/anaconda2/envs/megara/bin//numina", line 11, in <module>
    load_entry_point('numina==0.15.dev1', 'console_scripts', 'numina')()
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/cli.py", line 123, in main
    args.command(args, extra_args)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirun.py", line 86, in mode_run_obsmode
    mode_run_common(args, extra_args, mode='obs')
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 64, in mode_run_common
    return mode_run_common_obs(args, extra_args)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 177, in mode_run_common_obs
    workenv=workenv, task_control=task_control)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 214, in run_recipe
    completed_task = run_recipe_timed(recipe, rinput, task)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 232, in run_recipe_timed
    result = recipe.run(rinput)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/numina-0.15.dev1-py2.7-macosx-10.7-x86_64.egg/numina/core/validator.py", line 30, in mod_run
    result = method(self, ri)
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/megaradrp-0.6.dev1-py2.7.egg/megaradrp/recipes/calibration/trace.py", line 101, in run
    poldeg=rinput.polynomial_degree
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/megaradrp-0.6.dev1-py2.7.egg/megaradrp/recipes/calibration/trace.py", line 132, in search_traces
    threshold=threshold
  File "/Users/agpaz/anaconda2/envs/megara/lib/python2.7/site-packages/megaradrp-0.6.dev1-py2.7.egg/megaradrp/recipes/calibration/trace.py", line 307, in init_traces
    _logger.debug('peaks: %s \t %s', thispeaks[0, 1], thispeaks[last_matched_peak, 1])
IndexError: index 0 is out of bounds for axis 0 with size 0
[MacBook-Pro-de-Armando:MOS/ThNe/MR-R] agpaz%

**Comment by sergiopasra** [comment]
@guaix-ucm/megara-drp
