### ISSUE TITLE
Problem running in python3

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/megaradrp#129]
$ numina 
INFO: Numina simple recipe runner version 0.15.dev3
Traceback (most recent call last):
  File "/home/spr/.local/bin/numina", line 9, in <module>
    load_entry_point('numina==0.15.dev3', 'console_scripts', 'numina')()
  File "/home/spr/.local/lib/python3.5/site-packages/numina-0.15.dev3-py3.5-linux-x86_64.egg/numina/user/cli.py", line 123, in main
    args.command(args, extra_args)
AttributeError: 'Namespace' object has no attribute 'command'

**Comment by sergiopasra** [comment]
This is numina bug:  https://github.com/guaix-ucm/numina/issues/147
