### ISSUE TITLE
Model Map not created

### ISSUE THREAD

**Issue by pgomezalvarez** [guaix-ucm/megaradrp#163]
When trying to generate MEGARA Model Map:
`numina run 3_MegaraModelMap.yaml -r ../control.yaml `
With the following YAML

```
id: 3_LR_V_ModelMap
mode: MegaraModelMap
instrument: MEGARA
frames:
- 0001312112-20170830-MEGARA-MegaraLcbImage.fits
- 0001312113-20170830-MEGARA-MegaraLcbImage.fits
- 0001312114-20170830-MEGARA-MegaraLcbImage.fits
```

After some time... the process finished but with no output:

<img width="439" alt="screenshot 2017-12-05 15 07 29" src="https://user-images.githubusercontent.com/3682520/33614031-1a18bacc-d9ce-11e7-87e5-6550f7d74e2a.png">

The console output was:

```
(megara2_7) Pedro-MBP-2:tutorial pgomez$ numina run 3_MegaraModelMap.yaml -r ../control.yaml 

DEBUG: Numina simple recipe runner version 0.15.dev5
INFO: Loading observation results from '3_MegaraModelMap.yaml'
DEBUG: load observation result with id 3_LR_V_ModelMap
INFO: reading control from ../control.yaml
INFO: control format version 1
DEBUG: pipeline from CLI is 'default'
DEBUG: recipe class is <class 'megaradrp.recipes.calibration.modelmap.ModelMapRecipe'>
DEBUG: enable intermediate results
DEBUG: update recipe runinfo
DEBUG: recipe created
numina.dal.diskfiledal INFO search master_slitflat of type MasterSlitFlat()
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterSlitFlat/result.json
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterSlitFlat/master_sflat.fits
numina.dal.diskfiledal INFO found /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterSlitFlat/master_sflat.fits
/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterSlitFlat/master_sflat.fits
numina.dal.diskfiledal INFO search master_bias of type MasterBias()
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/result.json
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/.DS_Store
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/00_master_bias.fits
numina.dal.diskfiledal INFO found /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/00_master_bias.fits
/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/00_master_bias.fits
numina.dal.diskfiledal INFO search master_dark of type MasterDark()
numina.dal.diskfiledal INFO type MasterDark compatible with tags {'insmode': 'LCB', 'vph': 'LR-V'} not found
numina.dal.diskfiledal INFO search master_bpm of type MasterBPM()
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBPM/result.json
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBPM/master_bpm.fits
numina.dal.diskfiledal INFO found /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBPM/master_bpm.fits
/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBPM/master_bpm.fits
numina.dal.diskfiledal INFO search master_traces of type TraceMap()
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/TraceMap/LCB/LR-V/result.json
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/TraceMap/LCB/LR-V/.DS_Store
loadpath= /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/TraceMap/LCB/LR-V/00_master_traces.json
numina.dal.diskfiledal INFO found /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/TraceMap/LCB/LR-V/00_master_traces.json
/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/TraceMap/LCB/LR-V/00_master_traces.json
DEBUG: recipe input created
DEBUG: recipe requires 'processes', value is 0
DEBUG: recipe requires 'master_slitflat', value is DataFrame(filename=u'/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterSlitFlat/master_sflat.fits')
DEBUG: recipe requires 'debug_plot', value is 0
DEBUG: recipe requires 'master_bias', value is DataFrame(filename=u'/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/00_master_bias.fits')
DEBUG: recipe requires 'master_dark', value is None
DEBUG: recipe requires 'master_bpm', value is DataFrame(filename=u'/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBPM/master_bpm.fits')
DEBUG: recipe requires 'obresult', value is ObservationResult(id=3_LR_V_ModelMap, instrument=MEGARA, mode=MegaraModelMap)
DEBUG: recipe requires 'master_traces', value is TraceMap(instrument=MEGARA, uuid=8ca7f7b3-d8f5-11e7-9944-c4b301d558b3)
DEBUG: recipe provides ProcessedRSS, 
DEBUG: recipe provides QualityControlProduct, 
DEBUG: recipe provides ModelMap, 
DEBUG: recipe provides ProcessedImage, 
DEBUG: copy files to work directory
DEBUG: check workdir for working: '/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/tutorial/obsid3_LR_V_ModelMap_work'
DEBUG: check resultsdir to store results '/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/tutorial/obsid3_LR_V_ModelMap_results'
DEBUG: copying files from observation result
DEBUG: compute hash, 0001312112-20170830-MEGARA-MegaraLcbImage.fits 82cd6c68b4cf1ed87d6b5ba5165019c8 /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/tutorial/data/0001312112-20170830-MEGARA-MegaraLcbImage.fits
DEBUG: copying '0001312112-20170830-MEGARA-MegaraLcbImage.fits' not needed
DEBUG: compute hash, 0001312113-20170830-MEGARA-MegaraLcbImage.fits baee797b9cb0980f2705ddc520f8a8ec /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/tutorial/data/0001312113-20170830-MEGARA-MegaraLcbImage.fits
DEBUG: copying '0001312113-20170830-MEGARA-MegaraLcbImage.fits' not needed
DEBUG: compute hash, 0001312114-20170830-MEGARA-MegaraLcbImage.fits 4a6e51431284b87cd822dc4ba878af92 /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/tutorial/data/0001312114-20170830-MEGARA-MegaraLcbImage.fits
DEBUG: copying '0001312114-20170830-MEGARA-MegaraLcbImage.fits' not needed
DEBUG: copying files from requirements
DEBUG: compute hash, /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterSlitFlat/master_sflat.fits e2ed91a492b4e824aa53918f31d92eb0 /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterSlitFlat/master_sflat.fits
DEBUG: copying u'/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterSlitFlat/master_sflat.fits' not needed
DEBUG: compute hash, /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/00_master_bias.fits 3f0abd6d6c9134b577c2c1e153a3974e /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/00_master_bias.fits
DEBUG: copying u'/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBias/00_master_bias.fits' not needed
DEBUG: compute hash, /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBPM/master_bpm.fits 99c67f634cc95a3ac86f8e8a4a804874 /Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBPM/master_bpm.fits
DEBUG: copying u'/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/ca3558e3-e50d-4bbc-86bd-da50a0998a48/MasterBPM/master_bpm.fits' not needed
DEBUG: adapt observation result for work dir
DEBUG: creating file logger '/Users/pgomez/Fractal/Megara/MegaraCommissionning/dp/MEGARA/tutorial/obsid3_LR_V_ModelMap_results/processing.log' from Recipe logger
INFO: running recipe
numina.recipes.megara INFO starting model map recipe
numina.recipes.megara DEBUG using 6 processes
numina.recipes.megara INFO start basic reduction
numina.recipes.megara DEBUG get_filters, None  [<function get_corrector_overscan at 0x11dfd4320>, <function get_corrector_trimming at 0x11dfd4398>]
numina.recipes.megara DEBUG get_filters, <class 'megaradrp.types.MasterBPM'>  <function get_corrector_bpm at 0x11dfcd398>
numina.recipes.megara DEBUG get_filters, <class 'megaradrp.types.MasterBias'>  <function get_corrector_bias at 0x11dfd41b8>
numina.recipes.megara DEBUG get_filters, <class 'megaradrp.types.MasterDark'>  [<function get_corrector_dark at 0x11dfd4230>, <function get_corrector_gain at 0x11dfd4410>]
numina.recipes.megara DEBUG get_filters, <class 'megaradrp.types.MasterSlitFlat'>  <function get_corrector_slit_flat at 0x11dfd42a8>
numina.recipes.megara DEBUG obresult info
numina.recipes.megara DEBUG frame info is {'block_uuid': 'd9aa83f9-7dd1-420e-a2ac-b7313798e3fa', 'osfilter': 'BLUE', 'uuid': '3e2dc83c-4c5e-4f88-9551-290571c0cd76', 'vphpos': 'VPH10', 'insconf_uuid': 'ca3558e3-e50d-4bbc-86bd-da50a0998a48', 'insmode': 'LCB', 'speclamp': 'undefined', 'focus': 2313, 'exptime': 20.0, 'vph': 'LR-V', 'n_ext': 2, 'imgid': 'uuid:3e2dc83c-4c5e-4f88-9551-290571c0cd76', 'temp': 288.568478675517, 'observation_date': datetime.datetime(2017, 8, 30, 18, 49, 52, 160000), 'name_ext': ['PRIMARY', 'FIBERS']}
numina.recipes.megara DEBUG frame info is {'block_uuid': 'd9aa83f9-7dd1-420e-a2ac-b7313798e3fa', 'osfilter': 'BLUE', 'uuid': '1de8ccfd-227e-4d1c-9aaa-c0b2c722945d', 'vphpos': 'VPH10', 'insconf_uuid': 'ca3558e3-e50d-4bbc-86bd-da50a0998a48', 'insmode': 'LCB', 'speclamp': 'undefined', 'focus': 2313, 'exptime': 20.0, 'vph': 'LR-V', 'n_ext': 2, 'imgid': 'uuid:1de8ccfd-227e-4d1c-9aaa-c0b2c722945d', 'temp': 288.586789501793, 'observation_date': datetime.datetime(2017, 8, 30, 18, 51, 26, 460000), 'name_ext': ['PRIMARY', 'FIBERS']}
numina.recipes.megara DEBUG frame info is {'block_uuid': 'd9aa83f9-7dd1-420e-a2ac-b7313798e3fa', 'osfilter': 'BLUE', 'uuid': '901cb579-8ec2-468f-99ba-b138da4beba8', 'vphpos': 'VPH10', 'insconf_uuid': 'ca3558e3-e50d-4bbc-86bd-da50a0998a48', 'insmode': 'LCB', 'speclamp': 'undefined', 'focus': 2313, 'exptime': 20.0, 'vph': 'LR-V', 'n_ext': 2, 'imgid': 'uuid:901cb579-8ec2-468f-99ba-b138da4beba8', 'temp': 288.537960631723, 'observation_date': datetime.datetime(2017, 8, 30, 18, 53, 0, 790000), 'name_ext': ['PRIMARY', 'FIBERS']}
megaradrp.core.correctors INFO loading BPM
megaradrp.core.correctors DEBUG BPM image: uuid:20f77fc2-5a71-11e7-9d4f-f48c50066814
megaradrp.core.correctors INFO loading master_bias
megaradrp.core.correctors DEBUG master_bias info: {'block_uuid': None, 'osfilter': 'undefined', 'uuid': '6a929f0e-5aee-11e7-af9d-6c0b84a9a9d4', 'vphpos': 'undefined', 'insconf_uuid': 'ca3558e3-e50d-4bbc-86bd-da50a0998a48', 'insmode': 'undefined', 'speclamp': 'undefined', 'focus': 'undefined', 'exptime': 0.0, 'vph': 'undefined', 'n_ext': 1, 'imgid': 'uuid:6a929f0e-5aee-11e7-af9d-6c0b84a9a9d4', 'temp': 0.0, 'observation_date': datetime.datetime(1970, 1, 1, 0, 0), 'name_ext': ['PRIMARY']}
megaradrp.core.correctors INFO master_dark not provided, ignored
megaradrp.core.correctors INFO loading slit flat
megaradrp.core.correctors DEBUG master_slitflat image: {'block_uuid': None, 'osfilter': 'undefined', 'uuid': '0f172ddd-f1f7-41fc-8e17-55dd49da70af', 'vphpos': 'undefined', 'insconf_uuid': None, 'insmode': 'undefined', 'speclamp': 'undefined', 'focus': 'undefined', 'exptime': None, 'vph': 'undefined', 'n_ext': 1, 'imgid': 'uuid:0f172ddd-f1f7-41fc-8e17-55dd49da70af', 'temp': 0.0, 'observation_date': datetime.datetime(2017, 6, 22, 12, 0), 'name_ext': ['PRIMARY']}
megaradrp.processing.combine INFO processing input images
megaradrp.processing.combine INFO input is uuid:3e2dc83c-4c5e-4f88-9551-290571c0cd76
INFO: change dtype to float32, old is uint16
megaradrp.processing.trimover DEBUG prescan1 is 2073.328125
megaradrp.processing.trimover DEBUG col overscan1 is 2075.060303
megaradrp.processing.trimover DEBUG average scan1 is 2074.194336
megaradrp.processing.trimover DEBUG prescan2 is 2062.244873
megaradrp.processing.trimover DEBUG col overscan2 is 2029.184448
megaradrp.processing.trimover DEBUG average scan2 is 2045.714600
megaradrp.processing.trimover DEBUG trimming image uuid:3e2dc83c-4c5e-4f88-9551-290571c0cd76
DEBUG: correcting bad pixel mask in uuid:3e2dc83c-4c5e-4f88-9551-290571c0cd76
DEBUG: correcting bias in uuid:3e2dc83c-4c5e-4f88-9551-290571c0cd76
DEBUG: bias mean is 0.955180
megaradrp.processing.trimover DEBUG gain correction in image uuid:3e2dc83c-4c5e-4f88-9551-290571c0cd76
megaradrp.processing.fiberflat DEBUG correct slitflat in image uuid:3e2dc83c-4c5e-4f88-9551-290571c0cd76
megaradrp.processing.combine DEBUG output is input: False
megaradrp.processing.combine INFO input is uuid:1de8ccfd-227e-4d1c-9aaa-c0b2c722945d
INFO: change dtype to float32, old is uint16
megaradrp.processing.trimover DEBUG prescan1 is 2074.312744
megaradrp.processing.trimover DEBUG col overscan1 is 2076.042480
megaradrp.processing.trimover DEBUG average scan1 is 2075.177734
megaradrp.processing.trimover DEBUG prescan2 is 2063.413574
megaradrp.processing.trimover DEBUG col overscan2 is 2030.308228
megaradrp.processing.trimover DEBUG average scan2 is 2046.860840
megaradrp.processing.trimover DEBUG trimming image uuid:1de8ccfd-227e-4d1c-9aaa-c0b2c722945d
DEBUG: correcting bad pixel mask in uuid:1de8ccfd-227e-4d1c-9aaa-c0b2c722945d
DEBUG: correcting bias in uuid:1de8ccfd-227e-4d1c-9aaa-c0b2c722945d
DEBUG: bias mean is 0.955180
megaradrp.processing.trimover DEBUG gain correction in image uuid:1de8ccfd-227e-4d1c-9aaa-c0b2c722945d
megaradrp.processing.fiberflat DEBUG correct slitflat in image uuid:1de8ccfd-227e-4d1c-9aaa-c0b2c722945d
megaradrp.processing.combine DEBUG output is input: False
megaradrp.processing.combine INFO input is uuid:901cb579-8ec2-468f-99ba-b138da4beba8
INFO: change dtype to float32, old is uint16
megaradrp.processing.trimover DEBUG prescan1 is 2074.705078
megaradrp.processing.trimover DEBUG col overscan1 is 2076.425293
megaradrp.processing.trimover DEBUG average scan1 is 2075.565186
megaradrp.processing.trimover DEBUG prescan2 is 2063.769043
megaradrp.processing.trimover DEBUG col overscan2 is 2030.679321
megaradrp.processing.trimover DEBUG average scan2 is 2047.224121
megaradrp.processing.trimover DEBUG trimming image uuid:901cb579-8ec2-468f-99ba-b138da4beba8
DEBUG: correcting bad pixel mask in uuid:901cb579-8ec2-468f-99ba-b138da4beba8
DEBUG: correcting bias in uuid:901cb579-8ec2-468f-99ba-b138da4beba8
DEBUG: bias mean is 0.955180
megaradrp.processing.trimover DEBUG gain correction in image uuid:901cb579-8ec2-468f-99ba-b138da4beba8
megaradrp.processing.fiberflat DEBUG correct slitflat in image uuid:901cb579-8ec2-468f-99ba-b138da4beba8
megaradrp.processing.combine DEBUG output is input: False
megaradrp.processing.combine INFO stacking 3 images using 'median'
megaradrp.processing.combine DEBUG update result header
megaradrp.processing.combine DEBUG closing images
numina.recipes.megara INFO end basic reduction
numina.recipes.megara DEBUG create result model
numina.recipes.megara DEBUG update metadata in model
numina.recipes.megara INFO perform model fitting
calc_col is 100
calc_col is 200
calc_col is 300
calc_col is 400
calc_col is 500
calc_col is 600
calc_col is 700
calc_col is 800
calc_col is 900
calc_col is 1000
calc_col is 1100
calc_col is 1200
calc_col is 1300
calc_col is 1400
calc_col is 1500
calc_col is 1600
calc_col is 1700
calc_col is 1800
calc_col is 1900
calc_col is 2000
calc_col is 2100
calc_col is 2200
calc_col is 2300
calc_col is 2400
calc_col is 2500
calc_col is 2600
calc_col is 2700
calc_col is 2800
calc_col is 2900
calc_col is 3000
calc_col is 3100
calc_col is 3200
calc_col is 3300
calc_col is 3400
calc_col is 3500
calc_col is 3600
calc_col is 3700
calc_col is 3800
calc_col is 3900
calc_col is 4000
numina.recipes.megara INFO perform model fitting end
numina.recipes.megara INFO interpolate parameters
numina.recipes.megara DEBUG compute fibid 100
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 200
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 300
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 400
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 500
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 600
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara INFO interpolate parameters end
numina.recipes.megara INFO perform extraction with computed calibration
megaradrp.processing.aperture DEBUG advanced aperture extraction
megaradrp.processing.aperture DEBUG extracting (apextract_model) in image uuid:6533b900-d8ff-11e7-b198-c4b301d558b3
megaradrp.processing.aperture DEBUG with model map 659a093a-d8ff-11e7-829a-c4b301d558b3
megaradrp.processing.aperture DEBUG offsets are [ 0.]
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:26: RuntimeWarning: divide by zero encountered in true_divide
  z = (x - mean) / stddev
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:26: RuntimeWarning: invalid value encountered in true_divide
  z = (x - mean) / stddev
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:27: RuntimeWarning: divide by zero encountered in true_divide
  z2 = z + hpix / stddev
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:27: RuntimeWarning: invalid value encountered in add
  z2 = z + hpix / stddev
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:28: RuntimeWarning: divide by zero encountered in true_divide
  z1 = z - hpix / stddev
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:28: RuntimeWarning: invalid value encountered in subtract
  z1 = z - hpix / stddev
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1735: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0
The exact solution is  x = 0                              
The exact solution is  x = 0                              
/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numpy/linalg/linalg.py:2168: RuntimeWarning: invalid value encountered in sqrt
  ret = sqrt(sqnorm)
Traceback (most recent call last):
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/bin/numina", line 11, in <module>
    load_entry_point('numina==0.15.dev5', 'console_scripts', 'numina')()
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/cli.py", line 154, in main
    args.command(args, extra_args)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirun.py", line 108, in mode_run_obsmode
    mode_run_common(args, extra_args, mode='obs')
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 59, in mode_run_common
    return mode_run_common_obs(args, extra_args)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 197, in mode_run_common_obs
    workenv=workenv, task_control=task_control)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 232, in run_recipe
    completed_task = run_recipe_timed(recipe, rinput, task)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 246, in run_recipe_timed
    result = recipe(rinput)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/core/recipes.py", line 156, in __call__
    result = self.run(recipe_input)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/megaradrp-0.6.dev4-py2.7.egg/megaradrp/recipes/calibration/modelmap.py", line 193, in run
    reduced_rss = calibrator_aper(reduced_copy)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/flow/processing.py", line 82, in __call__
    img = self.run(img)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/megaradrp-0.6.dev4-py2.7.egg/megaradrp/processing/aperture.py", line 59, in run
    rssdata = self.tracemap.aper_extract(img[0].data, processes=self.processes)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/megaradrp-0.6.dev4-py2.7.egg/megaradrp/products/modelmap.py", line 102, in aper_extract
    return aper_extract(self, self._wcols, img)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/megaradrp-0.6.dev4-py2.7.egg/megaradrp/products/modelmap.py", line 267, in aper_extract
    res = lsqr(val, yl)
  File "/Users/pgomez/opt/anaconda/envs/megara2_7/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/lsqr.py", line 369, in lsqr
    cs1 = rhobar / rhobar1
ZeroDivisionError: float division by zero
(megara2_7) Pedro-MBP-2:tutorial pgomez$ 
```

**Comment by sergiopasra** [comment]
The message:

`
The exact solution is  x = 0
`

before the crash is very curious. 

I have tries to reproduce this but in my case, the recipe goes to the end.

What versions of scipy and numpy do you have?

**Comment by pgomezalvarez** [comment]
This is wath I get from the console in MEGARA environment:
```
(megara2_7) Pedro-MBP-2:tutorial pgomez$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy
>>> numpy.version.version
'1.13.0'
>>> import scipy
>>> scipy.version.version
'0.19.0'
>>> 
```

**Comment by pgomezalvarez** [comment]
I reinstalled numina and megaradrp alltogether. Now the packages are:
>>> import numpy
>>> numpy.version.version
'1.13.3'
>>> import scipy
>>> scipy.version.version
'1.0.0'

But the error stands...

**Comment by pgomezalvarez** [comment]
I Installed the conda from zero, created a new environment with Python3 and compiled the numina and megaradrp packages from scratch. Now the problem is gone :-)
The list of dependencies in this new environment is:

```
Pedro-MacBook-Pro-2:tutorial pgomez$ source activate megara3
(megara3) Pedro-MacBook-Pro-2:tutorial pgomez$ conda list
# packages in environment at /Users/pgomez/opt/anaconda/envs/megara3:
#
astropy                   2.0.2                     <pip>
attrs                     17.3.0                    <pip>
ca-certificates           2017.08.26           ha1e5d58_0  
certifi                   2017.11.5        py36ha569be9_0  
cycler                    0.10.0           py36hfc81398_0  
decorator                 4.1.2                     <pip>
freetype                  2.8                  h12048fb_1  
intel-openmp              2018.0.0             h8158457_8  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libpng                    1.6.32               hd1e8b91_4  
matplotlib                2.1.0                     <pip>
matplotlib                2.1.0            py36h5068139_0  
megaradrp                 0.6.dev4                  <pip>
mkl                       2018.0.1             hfbd8650_4  
ncurses                   6.0                  hd04f020_2  
networkx                  2.0                       <pip>
numina                    0.15.dev5                 <pip>
numpy                     1.13.3           py36h2cdce51_0  
openssl                   1.0.2m               h86d3e6a_1  
pip                       9.0.1            py36h1555ced_4  
pluggy                    0.6.0                     <pip>
py                        1.5.2                     <pip>
pyparsing                 2.2.0            py36hb281f35_0  
pytest                    3.3.1                     <pip>
python                    3.6.3                h5ce8c04_4  
python-dateutil           2.6.1            py36h86d2abb_1  
pytz                      2017.3           py36hf0bf824_0  
PyWavelets                0.5.2                     <pip>
readline                  7.0                  hc1231fa_4  
scikit-image              0.13.1                    <pip>
scipy                     1.0.0            py36h1de22e9_0  
setuptools                36.5.0           py36h2134326_0  
six                       1.11.0                    <pip>
six                       1.11.0           py36h0e22d5e_1  
sqlite                    3.20.1               h7e4c145_2  
tk                        8.6.7                h35a86e2_3  
tornado                   4.5.2            py36h468dda9_0  
wheel                     0.30.0           py36h5eb2c71_1  
xz                        5.2.3                h0278029_2  
zlib                      1.2.11               hf3cbc9b_2  
```

**Comment by sergiopasra** [comment]
It looks like a problem with some numerical library. Please, reopen if  you encounter this problem again

**Comment by pgomezalvarez** [comment]
It seems that also Ana was also affected. Could be related with a recent update I did to OsX High Sierra?

**Comment by gildepaz** [comment]
Same problem with me. I will be trying to fix it following Pedro's way!

**Comment by gildepaz** [comment]
I tried doing:
conda update conda
conda update scipy
conda update numpy
That put all the packages within the megara environment to versions equal or even more recent than those of Pedro but still the MegaraModelMap does not work (I still get "ZeroDivisionError: float division by zero" error"). 

I have also then tried:
conda remove --name megara --all
conda install -c sergiopasra/label/dev megaradrp
source activate megara
but it does not change any package, so it won't work (although I have executed just in case)

**Comment by gildepaz** [comment]
Indeed, it does not work yet. I will try with a deeper update (everything from scratch)

**Comment by gildepaz** [comment]
I finally made it work by installing anaconda3 (i.e. anaconda for Python3). In order to do that without removing the previous version (anaconda2) you can simply go to https://www.anaconda.com/download/ and install the anaconda for Python3. That would automatically change your .bash_profile to 
export PATH="$HOME/anaconda3/bin:$PATH" (instead of export PATH="$HOME/anaconda2/bin:$PATH"). If you add $HOME/anaconda3/bin to the "setenv PATH" of you .tcshrc you could also run "numina" within tcsh without any environment. 
Alternatively, the recommended option, is to create again the environment by doing "conda create --name megara" and then "source activate megara" in bash. 

You do not have to reinstall numina or megaradrp you can simply go to your github directory and do:
cd numina; git pull; python setup.py build; python setup.py install
cd ../megaradrp; git pull; python setup.py build; python setup.py install

That should be enough. So, in summary, if you are using a Mac, consider using the distribution for Python3. That should be included in the documentation / cookbook.
