### ISSUE TITLE
Crash when opening RSS in python 3

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/megaradrp#172]
target scale is 0.5 arcsec
Traceback (most recent call last):
  File "cube.py", line 472, in <module>
    main()
  File "cube.py", line 464, in main
    with fits.open(args.rss) as rss:
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1023, in _readfrom
    read_one = hdulist._read_next_hdu()
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1098, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 332, in readfrom
    **kwargs)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 397, in _readfrom_internal
    header = Header.fromfile(data, endcard=not ignore_missing_end)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/header.py", line 449, in fromfile
    padding)[1]
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/header.py", line 495, in _from_blocks
    end_found, block = cls._find_end_card(block, clen)
  File "/usr/lib64/python3.6/site-packages/astropy/io/fits/header.py", line 562, in _find_end_card
    for mo in HEADER_END_RE.finditer(block):
TypeError: cannot use a bytes pattern on a string-like object

**Comment by sergiopasra** [comment]
Issue in astropy: https://github.com/astropy/astropy/issues/7078
