### ISSUE TITLE
Error in ModelMap

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#178]
Running ModelMap yields the following error:

calc_col is 3900
calc_col is 4000
numina.recipes.megara INFO perform model fitting end
numina.recipes.megara INFO interpolate parameters
numina.recipes.megara DEBUG compute fibid 100
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 200
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 300
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 400
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 500
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara DEBUG compute fibid 600
numina.recipes.megara DEBUG saving plots
numina.recipes.megara DEBUG saving plots end
numina.recipes.megara INFO interpolate parameters end
numina.recipes.megara INFO perform extraction with computed calibration
megaradrp.processing.aperture DEBUG advanced aperture extraction
megaradrp.processing.aperture DEBUG extracting (apextract_model) in image uuid:ff8dc914-face-11e7-9aaf-f45c8999906d
megaradrp.processing.aperture DEBUG with model map ffed7bae-face-11e7-bfd9-f45c8999906d
megaradrp.processing.aperture DEBUG offsets are [ 0.]
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:26: RuntimeWarning: divide by zero encountered in true_divide
  z = (x - mean) / stddev
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:26: RuntimeWarning: invalid value encountered in true_divide
  z = (x - mean) / stddev
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:27: RuntimeWarning: divide by zero encountered in true_divide
  z2 = z + hpix / stddev
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:27: RuntimeWarning: invalid value encountered in add
  z2 = z + hpix / stddev
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:28: RuntimeWarning: divide by zero encountered in true_divide
  z1 = z - hpix / stddev
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/modeling/gaussbox.py:28: RuntimeWarning: invalid value encountered in subtract
  z1 = z - hpix / stddev
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1735: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0
The exact solution is  x = 0                              
The exact solution is  x = 0                              
/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py:2176: RuntimeWarning: invalid value encountered in sqrt
  ret = sqrt(sqnorm)
Traceback (most recent call last):
  File "/Users/nikkinoughani/anaconda/bin/numina", line 11, in <module>
    load_entry_point('numina==0.15.dev5', 'console_scripts', 'numina')()
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/cli.py", line 154, in main
    args.command(args, extra_args)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirun.py", line 108, in mode_run_obsmode
    mode_run_common(args, extra_args, mode='obs')
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 59, in mode_run_common
    return mode_run_common_obs(args, extra_args)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 197, in mode_run_common_obs
    workenv=workenv, task_control=task_control)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 232, in run_recipe
    completed_task = run_recipe_timed(recipe, rinput, task)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 246, in run_recipe_timed
    result = recipe(rinput)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/core/recipes.py", line 156, in __call__
    result = self.run(recipe_input)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/megaradrp-0.6.dev4-py2.7.egg/megaradrp/recipes/calibration/modelmap.py", line 193, in run
    reduced_rss = calibrator_aper(reduced_copy)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-macosx-10.7-x86_64.egg/numina/flow/processing.py", line 82, in __call__
    img = self.run(img)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/megaradrp-0.6.dev4-py2.7.egg/megaradrp/processing/aperture.py", line 59, in run
    rssdata = self.tracemap.aper_extract(img[0].data, processes=self.processes)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/megaradrp-0.6.dev4-py2.7.egg/megaradrp/products/modelmap.py", line 103, in aper_extract
    return aper_extract(self, self._wcols, img)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/megaradrp-0.6.dev4-py2.7.egg/megaradrp/products/modelmap.py", line 229, in aper_extract
    res = lsqr(val, yl)
  File "/Users/nikkinoughani/anaconda/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/lsqr.py", line 369, in lsqr
    cs1 = rhobar / rhobar1
ZeroDivisionError: float division by zero

**Comment by gildepaz** [comment]
Same as #163. Closed
