### ISSUE TITLE
Problems with cube.py under Python3

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#186]
Using cube.py under Python3 yields the following error (but works under Python2):

(megara) bash-3.2$ python cube.py -p 0.5 -o cube_BD33_LR-R.fits reduced_rss.fits 
target scale is 0.5 arcsec
Traceback (most recent call last):
  File "cube.py", line 472, in <module>
    main()
  File "cube.py", line 464, in main
    with fits.open(args.rss) as rss:
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1023, in _readfrom
    read_one = hdulist._read_next_hdu()
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1098, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 332, in readfrom
    **kwargs)
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 397, in _readfrom_internal
    header = Header.fromfile(data, endcard=not ignore_missing_end)
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/header.py", line 449, in fromfile
    padding)[1]
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/header.py", line 495, in _from_blocks
    end_found, block = cls._find_end_card(block, clen)
  File "/Users/agpaz/anaconda3/lib/python3.6/site-packages/astropy/io/fits/header.py", line 562, in _find_end_card
    for mo in HEADER_END_RE.finditer(block):
TypeError: cannot use a bytes pattern on a string-like object

**Comment by sergiopasra** [comment]
This is fixed in the last version of cube.py
