### ISSUE TITLE
After installing the stable version of the MEGARA pipeline, getting the error numina.util.flow' 

### ISSUE THREAD

**Issue by BillyTastroD** [guaix-ucm/megaradrp#209]
Hi Sergio

Help please.

I was able to install the stable MEGARA pipeline one my machine, still keeping the older environment. But I get this error  'ModuleNotFoundError: No module named 'numina.util.flow' when I run the wavelength calibration task. Same applies for the trace but a slightly different error: ModuleNotFoundError: No module named 'numina.frame.utils'

DEBUG: Numina simple recipe runner version 0.16.dev0
INFO: Loading observation results from 'Arc_7025_LRU_reduce.yaml'
DEBUG: load observation result with id Reduce_LRU_arc
INFO: reading control from control_7025.yaml
INFO: control format version 1
DEBUG: pipeline from CLI is 'default'
Traceback (most recent call last):
  File "/Users/bililigndullo/anaconda3/envs/megara/bin/numina", line 11, in <module>
    load_entry_point('numina==0.16.dev0', 'console_scripts', 'numina')()
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/user/cli.py", line 154, in main
    args.command(args, extra_args)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/user/clirun.py", line 108, in mode_run_obsmode
    mode_run_common(args, extra_args, mode='obs')
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 60, in mode_run_common
    return mode_run_common_obs(args, extra_args)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/user/clirundal.py", line 129, in mode_run_common_obs
    recipe = dal.search_recipe_from_ob(obsres)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/dal/absdal.py", line 75, in search_recipe_from_ob
    return self.search_recipe(instrument, mode, pipeline)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/dal/absdal.py", line 57, in search_recipe
    recipe = this_pipeline.get_recipe_object(mode)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/core/pipeline.py", line 80, in get_recipe_object
    recipe = self._get_base_object(recipe_entry)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/core/pipeline.py", line 60, in _get_base_object
    Cls = self._get_base_class(entry)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/core/pipeline.py", line 56, in _get_base_class
    return numina.core.objimport.import_object(recipe_fqn)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/numina-0.16.dev0-py3.6-macosx-10.7-x86_64.egg/numina/core/objimport.py", line 35, in import_object
    mm = importlib.import_module(mods)
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/megaradrp/recipes/scientific/lcb.py", line 18, in <module>
    from megaradrp.recipes.scientific.base import ImageRecipe
  File "/Users/bililigndullo/anaconda3/envs/megara/lib/python3.6/site-packages/megaradrp/recipes/scientific/base.py", line 15, in <module>
    from numina.util.flow import SerialFlow
ModuleNotFoundError: No module named 'numina.util.flow'

**Comment by sergiopasra** [comment]
You are running numina 0.16.dev0, please install numina 0.16
`
pip install numina==0.16
`
